version: "3.9"

services:
  mongo:
    build: ./build
    restart: always
    ports:
      - "${PORT}:27017"
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: admin

volumes:
  mongo_data: